/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 20:38:53 CEST 2018
 */

package org.ph394b8fe.validator.type.impl.regex_t;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.regex.PatternSyntaxException;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.ph394b8fe.validator.result.TResult;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class TTypeRx_ESTest extends TTypeRx_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 75 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I10 Branch 2 IFLE L67 - true
   * Goal 3. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I10 Branch 2 IFLE L67 - true in context: 
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false in context: 
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 67
   * Goal 12. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 73
   * Goal 13. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 75
   * Goal 14. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 15. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 85
   * Goal 16. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 17. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 91
   * Goal 18. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 19. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 20. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 21. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 22. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 23. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 24. Weak Mutation 12: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 25. Weak Mutation 13: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 26. Weak Mutation 14: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 27. Weak Mutation 15: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 28. Weak Mutation 16: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 29. Weak Mutation 17: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 30. Weak Mutation 18: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 31. Weak Mutation 19: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 32. Weak Mutation 20: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueTrue
   * Goal 33. Weak Mutation 21: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKey
   * Goal 34. Weak Mutation 22: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 35. Weak Mutation 23: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueFalse
   * Goal 36. Weak Mutation 24: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - InsertUnaryOp Negation of doesMatch
   * Goal 37. Weak Mutation 25: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - InsertUnaryOp IINC 1 doesMatch
   * Goal 38. Weak Mutation 26: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - InsertUnaryOp IINC -1 doesMatch
   * Goal 39. Weak Mutation 28: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - ReplaceComparisonOperator <= -> ==
   * Goal 40. Weak Mutation 46: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable iLine -> iColumn
   * Goal 41. Weak Mutation 47: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - InsertUnaryOp Negation of iLine
   * Goal 42. Weak Mutation 48: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - InsertUnaryOp IINC 1 iLine
   * Goal 43. Weak Mutation 49: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - InsertUnaryOp IINC -1 iLine
   * Goal 44. Weak Mutation 50: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable iColumn -> iLine
   * Goal 45. Weak Mutation 51: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - InsertUnaryOp Negation of iColumn
   * Goal 46. Weak Mutation 52: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - InsertUnaryOp IINC 1 iColumn
   * Goal 47. Weak Mutation 53: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - InsertUnaryOp IINC -1 iColumn
   * Goal 48. Weak Mutation 54: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> msgIfValidationFails
   * Goal 49. Weak Mutation 55: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> kValueTrue
   * Goal 50. Weak Mutation 56: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> kKey
   * Goal 51. Weak Mutation 57: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> kValueFalse
   * Goal 52. Weak Mutation 58: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 53. Weak Mutation 59: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> value
   * Goal 54. Weak Mutation 60: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 55. Weak Mutation 61: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 56. Weak Mutation 62: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 57. Weak Mutation 63: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> kValueFalse
   * Goal 58. Weak Mutation 64: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> kKeyOptionRegx
   * Goal 59. Weak Mutation 65: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> value
   * Goal 60. Weak Mutation 66: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 61. Weak Mutation 67: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:73 - ReplaceVariable msgIfValidationFails -> key
   * Goal 62. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 63. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 64. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 65. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 66. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 67. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 68. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 69. Weak Mutation 75: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> -1
   * Goal 70. Weak Mutation 78: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 71. Weak Mutation 79: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueTrue
   * Goal 72. Weak Mutation 80: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKey
   * Goal 73. Weak Mutation 81: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 74. Weak Mutation 82: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> key
   * Goal 75. Weak Mutation 83: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      TResult tResult0 = new TResult();
      tTypeRx0._withOption("regx", "");
      tTypeRx0._match("w", tResult0, 0, 1, "", "");
      assertTrue(tResult0.hasFatalities());
  }

  //Test case number: 1
  /*
   * 70 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I10 Branch 2 IFLE L67 - false
   * Goal 3. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I10 Branch 2 IFLE L67 - false in context: 
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false in context: 
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 67
   * Goal 12. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 69
   * Goal 13. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 70
   * Goal 14. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 75
   * Goal 15. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 16. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 85
   * Goal 17. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 18. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 91
   * Goal 19. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 20. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 21. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 22. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 23. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 24. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 25. Weak Mutation 12: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 26. Weak Mutation 13: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 27. Weak Mutation 14: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 28. Weak Mutation 15: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 29. Weak Mutation 16: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 30. Weak Mutation 17: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 31. Weak Mutation 18: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 32. Weak Mutation 19: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 33. Weak Mutation 20: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueTrue
   * Goal 34. Weak Mutation 21: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKey
   * Goal 35. Weak Mutation 22: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 36. Weak Mutation 23: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueFalse
   * Goal 37. Weak Mutation 24: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - InsertUnaryOp Negation of doesMatch
   * Goal 38. Weak Mutation 25: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - InsertUnaryOp IINC 1 doesMatch
   * Goal 39. Weak Mutation 26: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - InsertUnaryOp IINC -1 doesMatch
   * Goal 40. Weak Mutation 27: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:67 - ReplaceComparisonOperator <= -> -1
   * Goal 41. Weak Mutation 30: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable iLine -> iColumn
   * Goal 42. Weak Mutation 31: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - InsertUnaryOp Negation of iLine
   * Goal 43. Weak Mutation 32: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - InsertUnaryOp IINC 1 iLine
   * Goal 44. Weak Mutation 33: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - InsertUnaryOp IINC -1 iLine
   * Goal 45. Weak Mutation 34: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable iColumn -> iLine
   * Goal 46. Weak Mutation 35: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - InsertUnaryOp Negation of iColumn
   * Goal 47. Weak Mutation 36: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - InsertUnaryOp IINC 1 iColumn
   * Goal 48. Weak Mutation 37: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - InsertUnaryOp IINC -1 iColumn
   * Goal 49. Weak Mutation 38: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> msgIfValidationFails
   * Goal 50. Weak Mutation 39: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> kValueTrue
   * Goal 51. Weak Mutation 40: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> kKey
   * Goal 52. Weak Mutation 41: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> kValueFalse
   * Goal 53. Weak Mutation 42: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 54. Weak Mutation 43: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> value
   * Goal 55. Weak Mutation 44: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 56. Weak Mutation 45: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:69 - ReplaceConstant - Field matches rule (OK) -> 
   * Goal 57. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 58. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 59. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 60. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 61. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 62. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 63. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 64. Weak Mutation 75: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> -1
   * Goal 65. Weak Mutation 78: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 66. Weak Mutation 79: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueTrue
   * Goal 67. Weak Mutation 80: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKey
   * Goal 68. Weak Mutation 81: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 69. Weak Mutation 82: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> key
   * Goal 70. Weak Mutation 83: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      TResult tResult0 = new TResult();
      tTypeRx0._withOption("regx", "");
      tTypeRx0._match("", tResult0, 0, 1, "", "");
      assertFalse(tResult0.hasFatalities());
  }

  //Test case number: 2
  /*
   * 45 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: I4 Branch 1 IFNONNULL L49 - true
   * Goal 3. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: I4 Branch 1 IFNONNULL L49 - true in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:done()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false in context: 
   * Goal 7. done()V_java.util.regex.PatternSyntaxException_IMPLICIT
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 12. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 85
   * Goal 13. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 14. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 91
   * Goal 15. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 49
   * Goal 16. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 55
   * Goal 17. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: root-Branch
   * Goal 18. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 19. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V
   * Goal 20. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 21. Weak Mutation 0: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 22. Weak Mutation 1: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kValueTrue
   * Goal 23. Weak Mutation 2: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKey
   * Goal 24. Weak Mutation 3: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 25. Weak Mutation 4: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kValueFalse
   * Goal 26. Weak Mutation 5: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceComparisonOperator != null -> = null
   * Goal 27. Weak Mutation 7: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 28. Weak Mutation 8: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kValueTrue
   * Goal 29. Weak Mutation 9: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kKey
   * Goal 30. Weak Mutation 10: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 31. Weak Mutation 11: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kValueFalse
   * Goal 32. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 33. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 34. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 35. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 37. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 38. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 39. Weak Mutation 75: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> -1
   * Goal 40. Weak Mutation 78: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 41. Weak Mutation 79: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueTrue
   * Goal 42. Weak Mutation 80: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKey
   * Goal 43. Weak Mutation 81: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 44. Weak Mutation 82: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> key
   * Goal 45. Weak Mutation 83: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      tTypeRx0.withOption("regx", ")");
      // Undeclared exception!
      try { 
        tTypeRx0.done();
        fail("Expecting exception: PatternSyntaxException");
      
      } catch(PatternSyntaxException e) {
         //
         // Unmatched closing ')'
         // )
         //
         verifyException("java.util.regex.Pattern", e);
      }
  }

  //Test case number: 3
  /*
   * 18 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 3. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 5. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 6. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 12. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 13. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 14. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 15. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 16. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 17. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 18. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      // Undeclared exception!
      try { 
        tTypeRx0._withOption((String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 4
  /*
   * 45 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false in context: 
   * Goal 5. _match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V_java.util.regex.PatternSyntaxException_IMPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 12. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 85
   * Goal 13. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 14. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 91
   * Goal 15. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 16. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 17. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 18. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 19. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 20. Weak Mutation 12: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 21. Weak Mutation 13: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 22. Weak Mutation 14: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 23. Weak Mutation 15: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 24. Weak Mutation 16: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 25. Weak Mutation 17: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 26. Weak Mutation 18: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 27. Weak Mutation 19: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 28. Weak Mutation 20: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueTrue
   * Goal 29. Weak Mutation 21: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKey
   * Goal 30. Weak Mutation 22: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 31. Weak Mutation 23: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueFalse
   * Goal 32. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 33. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 34. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 35. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 37. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 38. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 39. Weak Mutation 75: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> -1
   * Goal 40. Weak Mutation 78: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 41. Weak Mutation 79: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueTrue
   * Goal 42. Weak Mutation 80: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKey
   * Goal 43. Weak Mutation 81: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 44. Weak Mutation 82: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> key
   * Goal 45. Weak Mutation 83: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      TResult tResult0 = new TResult();
      tTypeRx0._withOption("regx", "4{");
      // Undeclared exception!
      try { 
        tTypeRx0._match("", tResult0, 0, 0, "", (String) null);
        fail("Expecting exception: PatternSyntaxException");
      
      } catch(PatternSyntaxException e) {
         //
         // Illegal repetition near index 0
         // 4{
         // ^
         //
         verifyException("java.util.regex.Pattern", e);
      }
  }

  //Test case number: 5
  /*
   * 23 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 3. _match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 5. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 6. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 12. Weak Mutation 12: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 13. Weak Mutation 13: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 14. Weak Mutation 14: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 15. Weak Mutation 15: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 16. Weak Mutation 16: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 17. Weak Mutation 17: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 18. Weak Mutation 18: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 19. Weak Mutation 19: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 20. Weak Mutation 20: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueTrue
   * Goal 21. Weak Mutation 21: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKey
   * Goal 22. Weak Mutation 22: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 23. Weak Mutation 23: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      TResult tResult0 = new TResult();
      // Undeclared exception!
      try { 
        tTypeRx0._match("", tResult0, 0, 0, "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 6
  /*
   * 45 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false in context: 
   * Goal 5. _match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V_java.lang.IllegalArgumentException_IMPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 12. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 85
   * Goal 13. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 14. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 91
   * Goal 15. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 16. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 17. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 18. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 19. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 20. Weak Mutation 12: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 21. Weak Mutation 13: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 22. Weak Mutation 14: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 23. Weak Mutation 15: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 24. Weak Mutation 16: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 25. Weak Mutation 17: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 26. Weak Mutation 18: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 27. Weak Mutation 19: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 28. Weak Mutation 20: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueTrue
   * Goal 29. Weak Mutation 21: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKey
   * Goal 30. Weak Mutation 22: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 31. Weak Mutation 23: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable fPattern -> kValueFalse
   * Goal 32. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 33. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 34. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 35. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 37. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 38. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 39. Weak Mutation 75: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> -1
   * Goal 40. Weak Mutation 78: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 41. Weak Mutation 79: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueTrue
   * Goal 42. Weak Mutation 80: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKey
   * Goal 43. Weak Mutation 81: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 44. Weak Mutation 82: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> key
   * Goal 45. Weak Mutation 83: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      TResult tResult0 = new TResult();
      tTypeRx0._withOption("regx", "\"");
      // Undeclared exception!
      try { 
        tTypeRx0._match("", tResult0, 0, 0, "", "");
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
      }
  }

  //Test case number: 7
  /*
   * 28 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - true
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - true in context: 
   * Goal 5. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 89
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 15. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 16. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 17. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 18. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 19. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 20. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 21. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 22. Weak Mutation 76: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> ==
   * Goal 23. Weak Mutation 84: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:89 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 24. Weak Mutation 85: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:89 - ReplaceVariable key -> kValueTrue
   * Goal 25. Weak Mutation 86: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:89 - ReplaceVariable key -> value
   * Goal 26. Weak Mutation 87: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:89 - ReplaceVariable key -> kKey
   * Goal 27. Weak Mutation 88: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:89 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 28. Weak Mutation 89: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:89 - ReplaceVariable key -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      // Undeclared exception!
      try { 
        tTypeRx0._withOption("", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unknown option key: 
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 8
  /*
   * 21 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: I4 Branch 1 IFNONNULL L49 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: I4 Branch 1 IFNONNULL L49 - false in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:done()V
   * Goal 5. done()V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 49
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 51
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: root-Branch
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 15. Weak Mutation 0: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 16. Weak Mutation 1: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kValueTrue
   * Goal 17. Weak Mutation 2: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKey
   * Goal 18. Weak Mutation 3: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 19. Weak Mutation 4: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kValueFalse
   * Goal 20. Weak Mutation 5: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceComparisonOperator != null -> = null
   * Goal 21. Weak Mutation 6: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:51 - ReplaceConstant - regx -> 
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      // Undeclared exception!
      try { 
        tTypeRx0.done();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Missing option 'regx'. Did you call withOption (\"regx\", \"someValue\") ?
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 9
  /*
   * 47 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: I4 Branch 1 IFNONNULL L49 - true
   * Goal 3. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:<init>()V
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: I4 Branch 1 IFNONNULL L49 - true in context: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx:done()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 3 IFLE L83 - false in context: 
   * Goal 7. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 38
   * Goal 8. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 40
   * Goal 9. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V: Line 41
   * Goal 10. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 11. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 85
   * Goal 12. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 13. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 91
   * Goal 14. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 49
   * Goal 15. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 55
   * Goal 16. org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V: Line 56
   * Goal 17. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 18. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 19. [METHOD] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V
   * Goal 20. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.<init>()V
   * Goal 21. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 22. [METHODNOEX] org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V
   * Goal 23. Weak Mutation 0: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 24. Weak Mutation 1: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kValueTrue
   * Goal 25. Weak Mutation 2: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKey
   * Goal 26. Weak Mutation 3: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 27. Weak Mutation 4: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceVariable fPattern -> kValueFalse
   * Goal 28. Weak Mutation 5: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:49 - ReplaceComparisonOperator != null -> = null
   * Goal 29. Weak Mutation 7: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kKeyOptionRegx
   * Goal 30. Weak Mutation 8: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kValueTrue
   * Goal 31. Weak Mutation 9: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kKey
   * Goal 32. Weak Mutation 10: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kKeyOptionCanBeEmpty
   * Goal 33. Weak Mutation 11: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx.done()V:55 - ReplaceVariable fPattern -> kValueFalse
   * Goal 34. Weak Mutation 68: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionRegx
   * Goal 35. Weak Mutation 69: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueTrue
   * Goal 36. Weak Mutation 70: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> value
   * Goal 37. Weak Mutation 71: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKey
   * Goal 38. Weak Mutation 72: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 39. Weak Mutation 73: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable key -> kValueFalse
   * Goal 40. Weak Mutation 74: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceConstant - regx -> 
   * Goal 41. Weak Mutation 75: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceComparisonOperator <= -> -1
   * Goal 42. Weak Mutation 78: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionRegx
   * Goal 43. Weak Mutation 79: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueTrue
   * Goal 44. Weak Mutation 80: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKey
   * Goal 45. Weak Mutation 81: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 46. Weak Mutation 82: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> key
   * Goal 47. Weak Mutation 83: org.ph394b8fe.validator.type.impl.regex_t.TTypeRx._withOption(Ljava/lang/String;Ljava/lang/String;)V:85 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TTypeRx tTypeRx0 = new TTypeRx();
      tTypeRx0._withOption("regx", "");
      tTypeRx0.done();
  }
}
