/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 20:37:39 CEST 2018
 */

package org.ph394b8fe.validator.type.impl.void_t;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.ph394b8fe.validator.result.TResult;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class TTypeVoid_ESTest extends TTypeVoid_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 44 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - true
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - true in context: 
   * Goal 5. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 53
   * Goal 8. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 54
   * Goal 9. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 60
   * Goal 10. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 63
   * Goal 11. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 12. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 13. Weak Mutation 0: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> msgIfValidationFails
   * Goal 14. Weak Mutation 1: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueTrue
   * Goal 15. Weak Mutation 2: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKey
   * Goal 16. Weak Mutation 3: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 17. Weak Mutation 4: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> key
   * Goal 18. Weak Mutation 5: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueFalse
   * Goal 19. Weak Mutation 7: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceVariable len -> iLine
   * Goal 20. Weak Mutation 8: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp Negation of len
   * Goal 21. Weak Mutation 9: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC 1 len
   * Goal 22. Weak Mutation 10: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC -1 len
   * Goal 23. Weak Mutation 11: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceComparisonOperator > -> -2
   * Goal 24. Weak Mutation 31: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable iLine -> len
   * Goal 25. Weak Mutation 32: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable iLine -> iColumn
   * Goal 26. Weak Mutation 33: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp Negation of iLine
   * Goal 27. Weak Mutation 34: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC 1 iLine
   * Goal 28. Weak Mutation 35: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC -1 iLine
   * Goal 29. Weak Mutation 37: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable iColumn -> iLine
   * Goal 30. Weak Mutation 38: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp Negation of iColumn
   * Goal 31. Weak Mutation 39: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC 1 iColumn
   * Goal 32. Weak Mutation 40: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC -1 iColumn
   * Goal 33. Weak Mutation 41: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> msgIfValidationFails
   * Goal 34. Weak Mutation 42: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kValueTrue
   * Goal 35. Weak Mutation 43: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> value
   * Goal 36. Weak Mutation 44: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kKey
   * Goal 37. Weak Mutation 45: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 38. Weak Mutation 46: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kValueFalse
   * Goal 39. Weak Mutation 47: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 40. Weak Mutation 48: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> value
   * Goal 41. Weak Mutation 49: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 42. Weak Mutation 50: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 43. Weak Mutation 51: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> key
   * Goal 44. Weak Mutation 52: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      TResult tResult0 = new TResult();
      tTypeVoid0.match("8", tResult0, 0, 1, "", "");
      assertTrue(tResult0.hasFatalities());
  }

  //Test case number: 1
  /*
   * 38 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - false in context: 
   * Goal 5. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 53
   * Goal 8. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 54
   * Goal 9. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 56
   * Goal 10. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 57
   * Goal 11. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 63
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 15. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 16. Weak Mutation 1: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueTrue
   * Goal 17. Weak Mutation 2: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKey
   * Goal 18. Weak Mutation 3: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 19. Weak Mutation 5: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueFalse
   * Goal 20. Weak Mutation 6: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceVariable len -> iColumn
   * Goal 21. Weak Mutation 8: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp Negation of len
   * Goal 22. Weak Mutation 9: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC 1 len
   * Goal 23. Weak Mutation 10: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC -1 len
   * Goal 24. Weak Mutation 13: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceComparisonOperator > -> >=
   * Goal 25. Weak Mutation 15: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable iLine -> iColumn
   * Goal 26. Weak Mutation 16: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp Negation of iLine
   * Goal 27. Weak Mutation 17: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC 1 iLine
   * Goal 28. Weak Mutation 18: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC -1 iLine
   * Goal 29. Weak Mutation 19: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable iColumn -> len
   * Goal 30. Weak Mutation 20: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable iColumn -> iLine
   * Goal 31. Weak Mutation 21: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp Negation of iColumn
   * Goal 32. Weak Mutation 22: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC 1 iColumn
   * Goal 33. Weak Mutation 23: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC -1 iColumn
   * Goal 34. Weak Mutation 25: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kValueTrue
   * Goal 35. Weak Mutation 27: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 28: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 37. Weak Mutation 29: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kValueFalse
   * Goal 38. Weak Mutation 30: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceConstant - Field empty (OK) -> 
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      TResult tResult0 = new TResult();
      tTypeVoid0._match("", tResult0, 0, 1, "", "");
      assertFalse(tResult0.hasFatalities());
  }

  //Test case number: 2
  /*
   * 38 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - false in context: 
   * Goal 5. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 53
   * Goal 8. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 54
   * Goal 9. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 56
   * Goal 10. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 57
   * Goal 11. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 63
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 15. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 16. Weak Mutation 1: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueTrue
   * Goal 17. Weak Mutation 2: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKey
   * Goal 18. Weak Mutation 3: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 19. Weak Mutation 5: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueFalse
   * Goal 20. Weak Mutation 7: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceVariable len -> iLine
   * Goal 21. Weak Mutation 8: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp Negation of len
   * Goal 22. Weak Mutation 9: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC 1 len
   * Goal 23. Weak Mutation 10: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC -1 len
   * Goal 24. Weak Mutation 13: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceComparisonOperator > -> >=
   * Goal 25. Weak Mutation 14: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable iLine -> len
   * Goal 26. Weak Mutation 15: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable iLine -> iColumn
   * Goal 27. Weak Mutation 16: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp Negation of iLine
   * Goal 28. Weak Mutation 17: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC 1 iLine
   * Goal 29. Weak Mutation 18: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC -1 iLine
   * Goal 30. Weak Mutation 20: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable iColumn -> iLine
   * Goal 31. Weak Mutation 21: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp Negation of iColumn
   * Goal 32. Weak Mutation 22: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC 1 iColumn
   * Goal 33. Weak Mutation 23: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC -1 iColumn
   * Goal 34. Weak Mutation 25: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kValueTrue
   * Goal 35. Weak Mutation 27: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 28: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 37. Weak Mutation 29: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kValueFalse
   * Goal 38. Weak Mutation 30: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceConstant - Field empty (OK) -> 
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      TResult tResult0 = new TResult();
      tTypeVoid0._match("", tResult0, 1, 0, "", "");
      assertFalse(tResult0.hasFatalities());
  }

  //Test case number: 3
  /*
   * 37 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - false in context: 
   * Goal 5. _match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 8. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 53
   * Goal 9. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 54
   * Goal 10. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 56
   * Goal 11. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 15. Weak Mutation 0: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> msgIfValidationFails
   * Goal 16. Weak Mutation 1: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueTrue
   * Goal 17. Weak Mutation 2: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKey
   * Goal 18. Weak Mutation 3: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 19. Weak Mutation 4: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> key
   * Goal 20. Weak Mutation 5: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueFalse
   * Goal 21. Weak Mutation 8: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp Negation of len
   * Goal 22. Weak Mutation 9: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC 1 len
   * Goal 23. Weak Mutation 10: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC -1 len
   * Goal 24. Weak Mutation 13: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceComparisonOperator > -> >=
   * Goal 25. Weak Mutation 16: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp Negation of iLine
   * Goal 26. Weak Mutation 17: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC 1 iLine
   * Goal 27. Weak Mutation 18: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC -1 iLine
   * Goal 28. Weak Mutation 21: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp Negation of iColumn
   * Goal 29. Weak Mutation 22: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC 1 iColumn
   * Goal 30. Weak Mutation 23: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - InsertUnaryOp IINC -1 iColumn
   * Goal 31. Weak Mutation 24: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> msgIfValidationFails
   * Goal 32. Weak Mutation 25: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kValueTrue
   * Goal 33. Weak Mutation 26: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> value
   * Goal 34. Weak Mutation 27: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kKey
   * Goal 35. Weak Mutation 28: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 36. Weak Mutation 29: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceVariable key -> kValueFalse
   * Goal 37. Weak Mutation 30: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:56 - ReplaceConstant - Field empty (OK) -> 
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      // Undeclared exception!
      try { 
        tTypeVoid0._match("", (TResult) null, 0, 0, "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 4
  /*
   * 42 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - true
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I8 Branch 1 IFGT L54 - true in context: 
   * Goal 5. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 53
   * Goal 8. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 54
   * Goal 9. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 60
   * Goal 10. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 63
   * Goal 11. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 12. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 13. Weak Mutation 0: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> msgIfValidationFails
   * Goal 14. Weak Mutation 1: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueTrue
   * Goal 15. Weak Mutation 2: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKey
   * Goal 16. Weak Mutation 3: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 17. Weak Mutation 4: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> key
   * Goal 18. Weak Mutation 5: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:53 - ReplaceVariable value -> kValueFalse
   * Goal 19. Weak Mutation 6: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceVariable len -> iColumn
   * Goal 20. Weak Mutation 7: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceVariable len -> iLine
   * Goal 21. Weak Mutation 8: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp Negation of len
   * Goal 22. Weak Mutation 9: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC 1 len
   * Goal 23. Weak Mutation 10: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - InsertUnaryOp IINC -1 len
   * Goal 24. Weak Mutation 11: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:54 - ReplaceComparisonOperator > -> -2
   * Goal 25. Weak Mutation 31: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable iLine -> len
   * Goal 26. Weak Mutation 33: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp Negation of iLine
   * Goal 27. Weak Mutation 34: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC 1 iLine
   * Goal 28. Weak Mutation 35: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC -1 iLine
   * Goal 29. Weak Mutation 36: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable iColumn -> len
   * Goal 30. Weak Mutation 38: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp Negation of iColumn
   * Goal 31. Weak Mutation 39: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC 1 iColumn
   * Goal 32. Weak Mutation 40: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - InsertUnaryOp IINC -1 iColumn
   * Goal 33. Weak Mutation 42: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kValueTrue
   * Goal 34. Weak Mutation 43: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> value
   * Goal 35. Weak Mutation 44: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 45: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 37. Weak Mutation 46: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable key -> kValueFalse
   * Goal 38. Weak Mutation 47: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 39. Weak Mutation 48: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> value
   * Goal 40. Weak Mutation 49: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 41. Weak Mutation 50: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 42. Weak Mutation 52: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceVariable msgIfValidationFails -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      TResult tResult0 = new TResult();
      tTypeVoid0.match("k", tResult0, 0, 0, "", "");
      assertTrue(tResult0.hasFatalities());
  }

  //Test case number: 5
  /*
   * 15 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch in context: 
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 5. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 8. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 71
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 12. Weak Mutation 53: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kValueTrue
   * Goal 13. Weak Mutation 55: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKey
   * Goal 14. Weak Mutation 56: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 15. Weak Mutation 57: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid._withOption(Ljava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      // Undeclared exception!
      try { 
        tTypeVoid0._withOption("", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unknown option key: 
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 6
  /*
   * 11 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.done()V: root-Branch
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.done()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:done()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.void_t.TTypeVoid:<init>()V
   * Goal 5. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 33
   * Goal 6. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V: Line 35
   * Goal 7. org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.done()V: Line 43
   * Goal 8. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.done()V
   * Goal 10. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.<init>()V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.void_t.TTypeVoid.done()V
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TTypeVoid tTypeVoid0 = new TTypeVoid();
      tTypeVoid0.done();
  }
}
