/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 20:39:57 CEST 2018
 */

package org.ph394b8fe.validator.type.impl.int_t;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.ph394b8fe.validator.result.TResult;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class TTypeInt_ESTest extends TTypeInt_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 93 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false
   * Goal 3. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I45 Branch 2 IFEQ L74 - false
   * Goal 4. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I56 Branch 3 IFEQ L77 - false
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false in context: 
   * Goal 7. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I45 Branch 2 IFEQ L74 - false in context: 
   * Goal 8. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I56 Branch 3 IFEQ L77 - false in context: 
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 60
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 61
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 62
   * Goal 15. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 16. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 68
   * Goal 17. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 70
   * Goal 18. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 74
   * Goal 19. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 76
   * Goal 20. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 77
   * Goal 21. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 79
   * Goal 22. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 80
   * Goal 23. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 24. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 25. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 26. Weak Mutation 0: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceConstant - 1 -> 0
   * Goal 27. Weak Mutation 1: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:61 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 2: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp Negation of doContinue
   * Goal 29. Weak Mutation 3: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC 1 doContinue
   * Goal 30. Weak Mutation 4: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC -1 doContinue
   * Goal 31. Weak Mutation 5: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - ReplaceComparisonOperator == -> !=
   * Goal 32. Weak Mutation 6: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 33. Weak Mutation 7: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 34. Weak Mutation 8: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 35. Weak Mutation 9: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 36. Weak Mutation 10: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMin
   * Goal 37. Weak Mutation 11: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMax
   * Goal 38. Weak Mutation 12: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 39. Weak Mutation 13: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 40. Weak Mutation 15: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable iLine -> iColumn
   * Goal 41. Weak Mutation 16: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp Negation of iLine
   * Goal 42. Weak Mutation 17: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC 1 iLine
   * Goal 43. Weak Mutation 18: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC -1 iLine
   * Goal 44. Weak Mutation 19: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable iColumn -> x
   * Goal 45. Weak Mutation 20: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable iColumn -> iLine
   * Goal 46. Weak Mutation 21: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp Negation of iColumn
   * Goal 47. Weak Mutation 22: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC 1 iColumn
   * Goal 48. Weak Mutation 23: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC -1 iColumn
   * Goal 49. Weak Mutation 24: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> msgIfValidationFails
   * Goal 50. Weak Mutation 25: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kValueTrue
   * Goal 51. Weak Mutation 26: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKey
   * Goal 52. Weak Mutation 27: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kValueFalse
   * Goal 53. Weak Mutation 28: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionMin
   * Goal 54. Weak Mutation 29: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionMax
   * Goal 55. Weak Mutation 30: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> value
   * Goal 56. Weak Mutation 31: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 57. Weak Mutation 32: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 58. Weak Mutation 33: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 59. Weak Mutation 34: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kValueFalse
   * Goal 60. Weak Mutation 35: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionMin
   * Goal 61. Weak Mutation 36: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionMax
   * Goal 62. Weak Mutation 37: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> value
   * Goal 63. Weak Mutation 38: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 64. Weak Mutation 39: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> key
   * Goal 65. Weak Mutation 40: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceConstant - Details: Syntax error:  -> 
   * Goal 66. Weak Mutation 41: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp Negation of doContinue
   * Goal 67. Weak Mutation 42: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp IINC 1 doContinue
   * Goal 68. Weak Mutation 43: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp IINC -1 doContinue
   * Goal 69. Weak Mutation 44: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - ReplaceComparisonOperator == -> !=
   * Goal 70. Weak Mutation 45: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - ReplaceVariable x -> iColumn
   * Goal 71. Weak Mutation 47: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp Negation of x
   * Goal 72. Weak Mutation 48: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp IINC 1 x
   * Goal 73. Weak Mutation 49: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp IINC -1 x
   * Goal 74. Weak Mutation 51: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:77 - InsertUnaryOp Negation of isInRange
   * Goal 75. Weak Mutation 52: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:77 - ReplaceComparisonOperator == -> !=
   * Goal 76. Weak Mutation 54: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iLine -> iColumn
   * Goal 77. Weak Mutation 55: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp Negation of iLine
   * Goal 78. Weak Mutation 56: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 iLine
   * Goal 79. Weak Mutation 57: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 iLine
   * Goal 80. Weak Mutation 58: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iColumn -> x
   * Goal 81. Weak Mutation 59: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iColumn -> iLine
   * Goal 82. Weak Mutation 60: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp Negation of iColumn
   * Goal 83. Weak Mutation 61: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 iColumn
   * Goal 84. Weak Mutation 62: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 iColumn
   * Goal 85. Weak Mutation 63: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> msgIfValidationFails
   * Goal 86. Weak Mutation 64: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kValueTrue
   * Goal 87. Weak Mutation 65: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKey
   * Goal 88. Weak Mutation 66: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kValueFalse
   * Goal 89. Weak Mutation 67: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionMin
   * Goal 90. Weak Mutation 68: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionMax
   * Goal 91. Weak Mutation 69: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> value
   * Goal 92. Weak Mutation 70: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 93. Weak Mutation 71: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceConstant - Integer OK -> 
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      TResult tResult0 = new TResult();
      tTypeInt0.match("w", tResult0, 0, (-1), "", "");
      assertTrue(tResult0.hasFatalities());
      assertEquals(2, tResult0.getNumIssues());
  }

  //Test case number: 1
  /*
   * 93 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false
   * Goal 3. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I45 Branch 2 IFEQ L74 - false
   * Goal 4. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I56 Branch 3 IFEQ L77 - false
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false in context: 
   * Goal 7. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I45 Branch 2 IFEQ L74 - false in context: 
   * Goal 8. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I56 Branch 3 IFEQ L77 - false in context: 
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 60
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 61
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 62
   * Goal 15. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 16. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 68
   * Goal 17. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 70
   * Goal 18. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 74
   * Goal 19. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 76
   * Goal 20. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 77
   * Goal 21. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 79
   * Goal 22. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 80
   * Goal 23. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 24. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 25. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 26. Weak Mutation 0: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceConstant - 1 -> 0
   * Goal 27. Weak Mutation 1: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:61 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 2: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp Negation of doContinue
   * Goal 29. Weak Mutation 3: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC 1 doContinue
   * Goal 30. Weak Mutation 4: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC -1 doContinue
   * Goal 31. Weak Mutation 5: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - ReplaceComparisonOperator == -> !=
   * Goal 32. Weak Mutation 6: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 33. Weak Mutation 7: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 34. Weak Mutation 8: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 35. Weak Mutation 9: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 36. Weak Mutation 10: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMin
   * Goal 37. Weak Mutation 11: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMax
   * Goal 38. Weak Mutation 12: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 39. Weak Mutation 13: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 40. Weak Mutation 14: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable iLine -> x
   * Goal 41. Weak Mutation 15: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable iLine -> iColumn
   * Goal 42. Weak Mutation 16: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp Negation of iLine
   * Goal 43. Weak Mutation 17: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC 1 iLine
   * Goal 44. Weak Mutation 18: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC -1 iLine
   * Goal 45. Weak Mutation 20: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable iColumn -> iLine
   * Goal 46. Weak Mutation 21: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp Negation of iColumn
   * Goal 47. Weak Mutation 22: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC 1 iColumn
   * Goal 48. Weak Mutation 23: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC -1 iColumn
   * Goal 49. Weak Mutation 24: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> msgIfValidationFails
   * Goal 50. Weak Mutation 25: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kValueTrue
   * Goal 51. Weak Mutation 26: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKey
   * Goal 52. Weak Mutation 27: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kValueFalse
   * Goal 53. Weak Mutation 28: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionMin
   * Goal 54. Weak Mutation 29: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionMax
   * Goal 55. Weak Mutation 30: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> value
   * Goal 56. Weak Mutation 31: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 57. Weak Mutation 32: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 58. Weak Mutation 33: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 59. Weak Mutation 34: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kValueFalse
   * Goal 60. Weak Mutation 35: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionMin
   * Goal 61. Weak Mutation 36: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionMax
   * Goal 62. Weak Mutation 37: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> value
   * Goal 63. Weak Mutation 38: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 64. Weak Mutation 39: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> key
   * Goal 65. Weak Mutation 40: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceConstant - Details: Syntax error:  -> 
   * Goal 66. Weak Mutation 41: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp Negation of doContinue
   * Goal 67. Weak Mutation 42: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp IINC 1 doContinue
   * Goal 68. Weak Mutation 43: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp IINC -1 doContinue
   * Goal 69. Weak Mutation 44: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - ReplaceComparisonOperator == -> !=
   * Goal 70. Weak Mutation 46: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - ReplaceVariable x -> iLine
   * Goal 71. Weak Mutation 47: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp Negation of x
   * Goal 72. Weak Mutation 48: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp IINC 1 x
   * Goal 73. Weak Mutation 49: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp IINC -1 x
   * Goal 74. Weak Mutation 51: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:77 - InsertUnaryOp Negation of isInRange
   * Goal 75. Weak Mutation 52: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:77 - ReplaceComparisonOperator == -> !=
   * Goal 76. Weak Mutation 53: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iLine -> x
   * Goal 77. Weak Mutation 54: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iLine -> iColumn
   * Goal 78. Weak Mutation 55: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp Negation of iLine
   * Goal 79. Weak Mutation 56: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 iLine
   * Goal 80. Weak Mutation 57: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 iLine
   * Goal 81. Weak Mutation 59: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iColumn -> iLine
   * Goal 82. Weak Mutation 60: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp Negation of iColumn
   * Goal 83. Weak Mutation 61: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 iColumn
   * Goal 84. Weak Mutation 62: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 iColumn
   * Goal 85. Weak Mutation 63: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> msgIfValidationFails
   * Goal 86. Weak Mutation 64: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kValueTrue
   * Goal 87. Weak Mutation 65: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKey
   * Goal 88. Weak Mutation 66: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kValueFalse
   * Goal 89. Weak Mutation 67: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionMin
   * Goal 90. Weak Mutation 68: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionMax
   * Goal 91. Weak Mutation 69: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> value
   * Goal 92. Weak Mutation 70: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 93. Weak Mutation 71: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceConstant - Integer OK -> 
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      TResult tResult0 = new TResult();
      tTypeInt0.match("w", tResult0, (-1), 0, "", "");
      assertTrue(tResult0.hasFatalities());
      assertEquals(2, tResult0.getNumIssues());
  }

  //Test case number: 2
  /*
   * 68 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false
   * Goal 3. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I45 Branch 2 IFEQ L74 - false
   * Goal 4. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I56 Branch 3 IFEQ L77 - false
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false in context: 
   * Goal 7. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I45 Branch 2 IFEQ L74 - false in context: 
   * Goal 8. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I56 Branch 3 IFEQ L77 - false in context: 
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 60
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 61
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 62
   * Goal 15. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 16. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 67
   * Goal 17. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 74
   * Goal 18. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 76
   * Goal 19. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 77
   * Goal 20. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 79
   * Goal 21. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 80
   * Goal 22. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 86
   * Goal 23. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 24. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 25. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 26. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 27. Weak Mutation 0: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceConstant - 1 -> 0
   * Goal 28. Weak Mutation 1: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:61 - ReplaceConstant - 0 -> 1
   * Goal 29. Weak Mutation 2: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp Negation of doContinue
   * Goal 30. Weak Mutation 3: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC 1 doContinue
   * Goal 31. Weak Mutation 4: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC -1 doContinue
   * Goal 32. Weak Mutation 5: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - ReplaceComparisonOperator == -> !=
   * Goal 33. Weak Mutation 6: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 34. Weak Mutation 7: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 35. Weak Mutation 8: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 36. Weak Mutation 9: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 37. Weak Mutation 10: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMin
   * Goal 38. Weak Mutation 11: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMax
   * Goal 39. Weak Mutation 12: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 40. Weak Mutation 13: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 41. Weak Mutation 41: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp Negation of doContinue
   * Goal 42. Weak Mutation 42: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp IINC 1 doContinue
   * Goal 43. Weak Mutation 43: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - InsertUnaryOp IINC -1 doContinue
   * Goal 44. Weak Mutation 44: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:74 - ReplaceComparisonOperator == -> !=
   * Goal 45. Weak Mutation 45: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - ReplaceVariable x -> iColumn
   * Goal 46. Weak Mutation 46: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - ReplaceVariable x -> iLine
   * Goal 47. Weak Mutation 47: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp Negation of x
   * Goal 48. Weak Mutation 48: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp IINC 1 x
   * Goal 49. Weak Mutation 49: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:76 - InsertUnaryOp IINC -1 x
   * Goal 50. Weak Mutation 51: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:77 - InsertUnaryOp Negation of isInRange
   * Goal 51. Weak Mutation 52: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:77 - ReplaceComparisonOperator == -> !=
   * Goal 52. Weak Mutation 53: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iLine -> x
   * Goal 53. Weak Mutation 55: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp Negation of iLine
   * Goal 54. Weak Mutation 56: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 iLine
   * Goal 55. Weak Mutation 57: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 iLine
   * Goal 56. Weak Mutation 58: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable iColumn -> x
   * Goal 57. Weak Mutation 60: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp Negation of iColumn
   * Goal 58. Weak Mutation 61: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 iColumn
   * Goal 59. Weak Mutation 62: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 iColumn
   * Goal 60. Weak Mutation 63: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> msgIfValidationFails
   * Goal 61. Weak Mutation 64: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kValueTrue
   * Goal 62. Weak Mutation 65: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKey
   * Goal 63. Weak Mutation 66: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kValueFalse
   * Goal 64. Weak Mutation 67: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionMin
   * Goal 65. Weak Mutation 68: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionMax
   * Goal 66. Weak Mutation 69: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> value
   * Goal 67. Weak Mutation 70: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 68. Weak Mutation 71: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:79 - ReplaceConstant - Integer OK -> 
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      TResult tResult0 = new TResult();
      tTypeInt0._match("9", tResult0, 0, 0, "", "");
      assertEquals(1, tResult0.getNumIssues());
      assertFalse(tResult0.hasFatalities());
  }

  //Test case number: 3
  /*
   * 19 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 3. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 5. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 6. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 7. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 110
   * Goal 8. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 12. Weak Mutation 116: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueTrue
   * Goal 13. Weak Mutation 117: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKey
   * Goal 14. Weak Mutation 118: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueFalse
   * Goal 15. Weak Mutation 119: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMin
   * Goal 16. Weak Mutation 120: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMax
   * Goal 17. Weak Mutation 121: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> value
   * Goal 18. Weak Mutation 122: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 19. Weak Mutation 123: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceConstant - min -> 
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      // Undeclared exception!
      try { 
        tTypeInt0._withOption((String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 4
  /*
   * 53 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFEQ L62 - false in context: 
   * Goal 5. _match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 7. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 8. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 60
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 61
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 62
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 68
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 70
   * Goal 15. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 16. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 17. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 18. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 19. Weak Mutation 0: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:60 - ReplaceConstant - 1 -> 0
   * Goal 20. Weak Mutation 1: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:61 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 2: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp Negation of doContinue
   * Goal 22. Weak Mutation 3: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC 1 doContinue
   * Goal 23. Weak Mutation 4: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - InsertUnaryOp IINC -1 doContinue
   * Goal 24. Weak Mutation 5: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:62 - ReplaceComparisonOperator == -> !=
   * Goal 25. Weak Mutation 6: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 26. Weak Mutation 7: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 27. Weak Mutation 8: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 28. Weak Mutation 9: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 29. Weak Mutation 10: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMin
   * Goal 30. Weak Mutation 11: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionMax
   * Goal 31. Weak Mutation 12: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 32. Weak Mutation 13: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 33. Weak Mutation 16: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp Negation of iLine
   * Goal 34. Weak Mutation 17: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC 1 iLine
   * Goal 35. Weak Mutation 18: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC -1 iLine
   * Goal 36. Weak Mutation 21: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp Negation of iColumn
   * Goal 37. Weak Mutation 22: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC 1 iColumn
   * Goal 38. Weak Mutation 23: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - InsertUnaryOp IINC -1 iColumn
   * Goal 39. Weak Mutation 25: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kValueTrue
   * Goal 40. Weak Mutation 26: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKey
   * Goal 41. Weak Mutation 27: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kValueFalse
   * Goal 42. Weak Mutation 28: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionMin
   * Goal 43. Weak Mutation 29: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionMax
   * Goal 44. Weak Mutation 30: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> value
   * Goal 45. Weak Mutation 31: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 46. Weak Mutation 32: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 47. Weak Mutation 33: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 48. Weak Mutation 34: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kValueFalse
   * Goal 49. Weak Mutation 35: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionMin
   * Goal 50. Weak Mutation 36: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionMax
   * Goal 51. Weak Mutation 37: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> value
   * Goal 52. Weak Mutation 38: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 53. Weak Mutation 40: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:70 - ReplaceConstant - Details: Syntax error:  -> 
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      // Undeclared exception!
      try { 
        tTypeInt0._match("", (TResult) null, 0, 0, (String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 5
  /*
   * 42 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 4 IFLE L110 - true
   * Goal 3. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I19 Branch 5 IFLE L114 - true
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 4 IFLE L110 - true in context: 
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I19 Branch 5 IFLE L114 - true in context: 
   * Goal 7. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 8. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 110
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 114
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 120
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 15. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 16. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 17. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 18. Weak Mutation 116: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueTrue
   * Goal 19. Weak Mutation 117: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKey
   * Goal 20. Weak Mutation 118: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueFalse
   * Goal 21. Weak Mutation 119: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMin
   * Goal 22. Weak Mutation 120: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMax
   * Goal 23. Weak Mutation 121: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> value
   * Goal 24. Weak Mutation 122: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 25. Weak Mutation 123: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceConstant - min -> 
   * Goal 26. Weak Mutation 125: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceComparisonOperator <= -> ==
   * Goal 27. Weak Mutation 134: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kValueTrue
   * Goal 28. Weak Mutation 135: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKey
   * Goal 29. Weak Mutation 136: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kValueFalse
   * Goal 30. Weak Mutation 137: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKeyOptionMin
   * Goal 31. Weak Mutation 138: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKeyOptionMax
   * Goal 32. Weak Mutation 139: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> value
   * Goal 33. Weak Mutation 140: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 34. Weak Mutation 141: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceConstant - max -> 
   * Goal 35. Weak Mutation 143: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceComparisonOperator <= -> ==
   * Goal 36. Weak Mutation 152: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> kValueTrue
   * Goal 37. Weak Mutation 153: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> kKey
   * Goal 38. Weak Mutation 154: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> kValueFalse
   * Goal 39. Weak Mutation 155: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> kKeyOptionMin
   * Goal 40. Weak Mutation 156: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> kKeyOptionMax
   * Goal 41. Weak Mutation 157: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> value
   * Goal 42. Weak Mutation 158: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:120 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      // Undeclared exception!
      try { 
        tTypeInt0._withOption("", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unknown option key: 
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 6
  /*
   * 49 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V: root-Branch
   * Goal 3. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 4 IFLE L110 - true
   * Goal 4. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I19 Branch 5 IFLE L114 - false
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V: root-Branch in context: 
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 7. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 4 IFLE L110 - true in context: 
   * Goal 8. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I19 Branch 5 IFLE L114 - false in context: 
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V: Line 92
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 110
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 114
   * Goal 15. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 116
   * Goal 16. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 17. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 18. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 19. Weak Mutation 98: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V:92 - ReplaceVariable x -> kValueTrue
   * Goal 20. Weak Mutation 99: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V:92 - ReplaceVariable x -> kKey
   * Goal 21. Weak Mutation 100: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V:92 - ReplaceVariable x -> kValueFalse
   * Goal 22. Weak Mutation 101: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V:92 - ReplaceVariable x -> kKeyOptionMin
   * Goal 23. Weak Mutation 102: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V:92 - ReplaceVariable x -> kKeyOptionMax
   * Goal 24. Weak Mutation 103: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMax(Ljava/lang/String;)V:92 - ReplaceVariable x -> kKeyOptionCanBeEmpty
   * Goal 25. Weak Mutation 116: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueTrue
   * Goal 26. Weak Mutation 117: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKey
   * Goal 27. Weak Mutation 118: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueFalse
   * Goal 28. Weak Mutation 119: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMin
   * Goal 29. Weak Mutation 120: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMax
   * Goal 30. Weak Mutation 121: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> value
   * Goal 31. Weak Mutation 122: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 32. Weak Mutation 123: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceConstant - min -> 
   * Goal 33. Weak Mutation 125: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceComparisonOperator <= -> ==
   * Goal 34. Weak Mutation 134: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kValueTrue
   * Goal 35. Weak Mutation 135: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKey
   * Goal 36. Weak Mutation 136: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kValueFalse
   * Goal 37. Weak Mutation 137: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKeyOptionMin
   * Goal 38. Weak Mutation 138: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKeyOptionMax
   * Goal 39. Weak Mutation 139: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> value
   * Goal 40. Weak Mutation 140: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 41. Weak Mutation 141: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceConstant - max -> 
   * Goal 42. Weak Mutation 142: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:114 - ReplaceComparisonOperator <= -> -1
   * Goal 43. Weak Mutation 145: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> kValueTrue
   * Goal 44. Weak Mutation 146: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> kKey
   * Goal 45. Weak Mutation 147: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> kValueFalse
   * Goal 46. Weak Mutation 148: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> kKeyOptionMin
   * Goal 47. Weak Mutation 149: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> kKeyOptionMax
   * Goal 48. Weak Mutation 150: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 49. Weak Mutation 151: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:116 - ReplaceVariable value -> key
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      // Undeclared exception!
      try { 
        tTypeInt0.withOption("max", "");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  //Test case number: 7
  /*
   * 12 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.done()V: root-Branch
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.done()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:done()V
   * Goal 5. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 6. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 7. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 8. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.done()V: Line 48
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.done()V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 12. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.done()V
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      tTypeInt0.done();
  }

  //Test case number: 8
  /*
   * 39 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V: root-Branch
   * Goal 3. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 4 IFLE L110 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V: root-Branch in context: 
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.int_t.TTypeInt:<init>()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 4 IFLE L110 - false in context: 
   * Goal 7. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.NumberFormatException_IMPLICIT
   * Goal 8. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 37
   * Goal 9. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 39
   * Goal 10. org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V: Line 40
   * Goal 11. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V: Line 100
   * Goal 12. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 110
   * Goal 13. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 112
   * Goal 14. org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 15. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 16. [METHOD] org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 17. [METHODNOEX] org.ph394b8fe.validator.type.impl.int_t.TTypeInt.<init>()V
   * Goal 18. Weak Mutation 107: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V:100 - ReplaceVariable x -> kValueTrue
   * Goal 19. Weak Mutation 108: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V:100 - ReplaceVariable x -> kKey
   * Goal 20. Weak Mutation 109: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V:100 - ReplaceVariable x -> kValueFalse
   * Goal 21. Weak Mutation 110: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V:100 - ReplaceVariable x -> kKeyOptionMin
   * Goal 22. Weak Mutation 111: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V:100 - ReplaceVariable x -> kKeyOptionMax
   * Goal 23. Weak Mutation 112: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._setConstraintMin(Ljava/lang/String;)V:100 - ReplaceVariable x -> kKeyOptionCanBeEmpty
   * Goal 24. Weak Mutation 116: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueTrue
   * Goal 25. Weak Mutation 117: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKey
   * Goal 26. Weak Mutation 118: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kValueFalse
   * Goal 27. Weak Mutation 119: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMin
   * Goal 28. Weak Mutation 120: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionMax
   * Goal 29. Weak Mutation 121: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> value
   * Goal 30. Weak Mutation 122: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 31. Weak Mutation 123: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceConstant - min -> 
   * Goal 32. Weak Mutation 124: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:110 - ReplaceComparisonOperator <= -> -1
   * Goal 33. Weak Mutation 127: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> kValueTrue
   * Goal 34. Weak Mutation 128: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> kKey
   * Goal 35. Weak Mutation 129: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> kValueFalse
   * Goal 36. Weak Mutation 130: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> kKeyOptionMin
   * Goal 37. Weak Mutation 131: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> kKeyOptionMax
   * Goal 38. Weak Mutation 132: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 39. Weak Mutation 133: org.ph394b8fe.validator.type.impl.int_t.TTypeInt._withOption(Ljava/lang/String;Ljava/lang/String;)V:112 - ReplaceVariable value -> key
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TTypeInt tTypeInt0 = new TTypeInt();
      // Undeclared exception!
      try { 
        tTypeInt0._withOption("min", "");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }
}
