/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 20:42:17 CEST 2018
 */

package org.ph394b8fe.validator.type.impl.datetime_t;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.ph394b8fe.validator.result.TResult;
import org.ph394b8fe.validator.type.VType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class TTypeDateTime_ESTest extends TTypeDateTime_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 63 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 3. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch in context: 
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false in context: 
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 69
   * Goal 12. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 71
   * Goal 13. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 73
   * Goal 14. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 15. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 16. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 84
   * Goal 17. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 89
   * Goal 18. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 19. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 20. Weak Mutation 2: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 21. Weak Mutation 3: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 22. Weak Mutation 4: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 23. Weak Mutation 5: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 24. Weak Mutation 6: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 25. Weak Mutation 7: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 26. Weak Mutation 8: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 27. Weak Mutation 25: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable iLine -> iColumn
   * Goal 28. Weak Mutation 26: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp Negation of iLine
   * Goal 29. Weak Mutation 27: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC 1 iLine
   * Goal 30. Weak Mutation 28: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC -1 iLine
   * Goal 31. Weak Mutation 29: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable iColumn -> iLine
   * Goal 32. Weak Mutation 30: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp Negation of iColumn
   * Goal 33. Weak Mutation 31: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC 1 iColumn
   * Goal 34. Weak Mutation 32: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC -1 iColumn
   * Goal 35. Weak Mutation 33: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> msgIfValidationFails
   * Goal 36. Weak Mutation 34: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kValueTrue
   * Goal 37. Weak Mutation 35: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKey
   * Goal 38. Weak Mutation 36: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kValueFalse
   * Goal 39. Weak Mutation 37: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 40. Weak Mutation 38: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> value
   * Goal 41. Weak Mutation 39: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 42. Weak Mutation 40: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 43. Weak Mutation 41: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 44. Weak Mutation 42: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kValueFalse
   * Goal 45. Weak Mutation 43: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kKeyOptionFormat
   * Goal 46. Weak Mutation 44: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> value
   * Goal 47. Weak Mutation 45: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 48. Weak Mutation 46: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> key
   * Goal 49. Weak Mutation 47: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceConstant - . Details:  -> 
   * Goal 50. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 51. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 52. Weak Mutation 50: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> value
   * Goal 53. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 54. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 55. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 56. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   * Goal 57. Weak Mutation 55: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceComparisonOperator <= -> -1
   * Goal 58. Weak Mutation 58: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueTrue
   * Goal 59. Weak Mutation 59: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 60. Weak Mutation 60: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKey
   * Goal 61. Weak Mutation 61: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 62. Weak Mutation 62: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> key
   * Goal 63. Weak Mutation 63: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      VType vType0 = tTypeDateTime0.withOption("format", "");
      TResult tResult0 = new TResult();
      vType0.match("s", tResult0, 0, (-1), "", "");
      assertSame(vType0, tTypeDateTime0);
  }

  //Test case number: 1
  /*
   * 29 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false in context: 
   * Goal 5. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 6. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 84
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 89
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 15. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 16. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 17. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 18. Weak Mutation 50: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> value
   * Goal 19. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 20. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 21. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 22. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   * Goal 23. Weak Mutation 55: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceComparisonOperator <= -> -1
   * Goal 24. Weak Mutation 58: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueTrue
   * Goal 25. Weak Mutation 59: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 26. Weak Mutation 60: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKey
   * Goal 27. Weak Mutation 61: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 28. Weak Mutation 62: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> key
   * Goal 29. Weak Mutation 63: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      tTypeDateTime0._withOption("format", "");
  }

  //Test case number: 2
  /*
   * 63 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 3. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch in context: 
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false in context: 
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 69
   * Goal 12. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 71
   * Goal 13. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 73
   * Goal 14. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 15. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 16. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 84
   * Goal 17. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 89
   * Goal 18. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 19. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 20. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 21. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 22. Weak Mutation 2: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> msgIfValidationFails
   * Goal 23. Weak Mutation 3: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 24. Weak Mutation 4: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 25. Weak Mutation 5: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 26. Weak Mutation 6: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 27. Weak Mutation 7: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 28. Weak Mutation 8: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> key
   * Goal 29. Weak Mutation 26: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp Negation of iLine
   * Goal 30. Weak Mutation 27: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC 1 iLine
   * Goal 31. Weak Mutation 28: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC -1 iLine
   * Goal 32. Weak Mutation 30: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp Negation of iColumn
   * Goal 33. Weak Mutation 31: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC 1 iColumn
   * Goal 34. Weak Mutation 32: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - InsertUnaryOp IINC -1 iColumn
   * Goal 35. Weak Mutation 33: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> msgIfValidationFails
   * Goal 36. Weak Mutation 34: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kValueTrue
   * Goal 37. Weak Mutation 35: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKey
   * Goal 38. Weak Mutation 36: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kValueFalse
   * Goal 39. Weak Mutation 37: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 40. Weak Mutation 38: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> value
   * Goal 41. Weak Mutation 39: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 42. Weak Mutation 40: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kValueTrue
   * Goal 43. Weak Mutation 41: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kKey
   * Goal 44. Weak Mutation 42: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kValueFalse
   * Goal 45. Weak Mutation 43: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kKeyOptionFormat
   * Goal 46. Weak Mutation 44: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> value
   * Goal 47. Weak Mutation 45: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> kKeyOptionCanBeEmpty
   * Goal 48. Weak Mutation 46: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceVariable msgIfValidationFails -> key
   * Goal 49. Weak Mutation 47: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:71 - ReplaceConstant - . Details:  -> 
   * Goal 50. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 51. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 52. Weak Mutation 50: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> value
   * Goal 53. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 54. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 55. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 56. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   * Goal 57. Weak Mutation 55: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceComparisonOperator <= -> -1
   * Goal 58. Weak Mutation 58: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueTrue
   * Goal 59. Weak Mutation 59: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 60. Weak Mutation 60: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKey
   * Goal 61. Weak Mutation 61: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 62. Weak Mutation 62: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> key
   * Goal 63. Weak Mutation 63: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      VType vType0 = tTypeDateTime0.withOption("format", "");
      TResult tResult0 = new TResult();
      tTypeDateTime0._match("", tResult0, 0, 0, "", "");
      assertSame(tTypeDateTime0, vType0);
  }

  //Test case number: 3
  /*
   * 17 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 2. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 3. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 5. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 6. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 9. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 11. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 12. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 13. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 14. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 15. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 16. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 17. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      // Undeclared exception!
      try { 
        tTypeDateTime0._withOption((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 4
  /*
   * 28 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false in context: 
   * Goal 5. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.IllegalArgumentException_IMPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 15. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 16. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 17. Weak Mutation 50: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> value
   * Goal 18. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 19. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 20. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 21. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   * Goal 22. Weak Mutation 55: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceComparisonOperator <= -> -1
   * Goal 23. Weak Mutation 58: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueTrue
   * Goal 24. Weak Mutation 59: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 25. Weak Mutation 60: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKey
   * Goal 26. Weak Mutation 61: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 27. Weak Mutation 62: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> key
   * Goal 28. Weak Mutation 63: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      // Undeclared exception!
      try { 
        tTypeDateTime0._withOption("format", "f");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unknown pattern letter: f
         //
         verifyException("java.time.format.DateTimeFormatterBuilder", e);
      }
  }

  //Test case number: 5
  /*
   * 28 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - true
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - true in context: 
   * Goal 5. _withOption(Ljava/lang/String;Ljava/lang/String;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 87
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 15. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 16. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 17. Weak Mutation 50: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> value
   * Goal 18. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 19. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 20. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 21. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   * Goal 22. Weak Mutation 56: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceComparisonOperator <= -> ==
   * Goal 23. Weak Mutation 64: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:87 - ReplaceVariable key -> kValueTrue
   * Goal 24. Weak Mutation 65: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:87 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 25. Weak Mutation 66: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:87 - ReplaceVariable key -> value
   * Goal 26. Weak Mutation 67: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:87 - ReplaceVariable key -> kKey
   * Goal 27. Weak Mutation 68: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:87 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 28. Weak Mutation 69: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:87 - ReplaceVariable key -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      // Undeclared exception!
      try { 
        tTypeDateTime0._withOption("", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unknown option key: 
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 6
  /*
   * 16 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: I4 Branch 1 IFNONNULL L52 - false
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: I4 Branch 1 IFNONNULL L52 - false in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:done()V
   * Goal 5. done()V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: Line 52
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: Line 54
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: root-Branch
   * Goal 12. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 13. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V
   * Goal 14. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 15. Weak Mutation 0: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V:52 - ReplaceComparisonOperator != null -> = null
   * Goal 16. Weak Mutation 1: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V:54 - ReplaceConstant - format -> 
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      // Undeclared exception!
      try { 
        tTypeDateTime0.done();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Missing option 'format'. Did you call withOption (\"format\", \"someValue\") ?
         //
         verifyException("org.ph394b8fe.validator.type.VType", e);
      }
  }

  //Test case number: 7
  /*
   * 34 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: I4 Branch 1 IFNONNULL L52 - true
   * Goal 3. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 5. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: I4 Branch 1 IFNONNULL L52 - true in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:done()V
   * Goal 6. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 2 IFLE L81 - false in context: 
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 10. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 81
   * Goal 11. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 83
   * Goal 12. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 84
   * Goal 13. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V: Line 89
   * Goal 14. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: Line 52
   * Goal 15. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V: Line 56
   * Goal 16. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 17. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V
   * Goal 18. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 19. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V
   * Goal 20. Weak Mutation 0: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.done()V:52 - ReplaceComparisonOperator != null -> = null
   * Goal 21. Weak Mutation 48: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueTrue
   * Goal 22. Weak Mutation 49: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionFormat
   * Goal 23. Weak Mutation 50: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> value
   * Goal 24. Weak Mutation 51: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKey
   * Goal 25. Weak Mutation 52: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kKeyOptionCanBeEmpty
   * Goal 26. Weak Mutation 53: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceVariable key -> kValueFalse
   * Goal 27. Weak Mutation 54: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceConstant - format -> 
   * Goal 28. Weak Mutation 55: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:81 - ReplaceComparisonOperator <= -> -1
   * Goal 29. Weak Mutation 58: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueTrue
   * Goal 30. Weak Mutation 59: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 31. Weak Mutation 60: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKey
   * Goal 32. Weak Mutation 61: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   * Goal 33. Weak Mutation 62: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> key
   * Goal 34. Weak Mutation 63: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._withOption(Ljava/lang/String;Ljava/lang/String;)V:83 - ReplaceVariable value -> kValueFalse
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      VType vType0 = tTypeDateTime0.withOption("format", "");
      vType0.done();
      assertSame(tTypeDateTime0, vType0);
  }

  //Test case number: 8
  /*
   * 17 covered goals:
   * Goal 1. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch
   * Goal 2. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch
   * Goal 3. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: root-Branch in context: 
   * Goal 4. Branch org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: root-Branch in context: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime:<init>()V
   * Goal 5. _match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 6. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 41
   * Goal 7. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 43
   * Goal 8. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V: Line 44
   * Goal 9. org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V: Line 66
   * Goal 10. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 11. [METHOD] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V
   * Goal 12. [METHODNOEX] org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime.<init>()V
   * Goal 13. Weak Mutation 3: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueTrue
   * Goal 14. Weak Mutation 4: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKey
   * Goal 15. Weak Mutation 5: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kValueFalse
   * Goal 16. Weak Mutation 6: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionFormat
   * Goal 17. Weak Mutation 7: org.ph394b8fe.validator.type.impl.datetime_t.TTypeDateTime._match(Ljava/lang/String;Lorg/ph394b8fe/validator/result/TResult;IILjava/lang/String;Ljava/lang/String;)V:66 - ReplaceVariable value -> kKeyOptionCanBeEmpty
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TTypeDateTime tTypeDateTime0 = new TTypeDateTime();
      TResult tResult0 = new TResult();
      // Undeclared exception!
      try { 
        tTypeDateTime0._match("", tResult0, 0, 0, "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // formatter
         //
         verifyException("java.util.Objects", e);
      }
  }
}
