/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 20:35:52 CEST 2018
 */

package org.ph394b8fe.validator;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.ph394b8fe.TReceptacleStdOut;
import org.ph394b8fe.validator.policy.TPolicy;
import org.ph394b8fe.validator.result.TResult;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class TCSVValidator_ESTest extends TCSVValidator_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.ph394b8fe.validator.TCSVValidator.IReceptacle.push(Lorg/ph394b8fe/validator/result/TResult;)V
   * Goal 2. [METHODNOEX] org.ph394b8fe.validator.TCSVValidator.IReceptacle.push(Lorg/ph394b8fe/validator/result/TResult;)V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TReceptacleStdOut tReceptacleStdOut0 = new TReceptacleStdOut(true);
      TResult tResult0 = new TResult();
      tReceptacleStdOut0.push(tResult0);
      assertEquals(0, tResult0.getNumIssues());
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * Goal 1. <init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 28
   * Goal 3. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 32
   * Goal 4. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: root-Branch
   * Goal 5. [METHOD] org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TCSVValidator tCSVValidator0 = null;
      try {
        tCSVValidator0 = new TCSVValidator((TPolicy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ph394b8fe.validator.TCSVValidator", e);
      }
  }

  //Test case number: 2
  /*
   * 10 covered goals:
   * Goal 1. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: I12 Branch 1 IFEQ L33 - true
   * Goal 2. Branch org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: I12 Branch 1 IFEQ L33 - true in context: org.ph394b8fe.validator.TCSVValidator:<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V
   * Goal 3. <init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 4. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 28
   * Goal 5. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 32
   * Goal 6. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 33
   * Goal 7. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 39
   * Goal 8. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 40
   * Goal 9. org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V: Line 41
   * Goal 10. [METHOD] org.ph394b8fe.validator.TCSVValidator.<init>(Lorg/ph394b8fe/validator/policy/TPolicy;)V
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TPolicy tPolicy0 = new TPolicy();
      TCSVValidator tCSVValidator0 = null;
      try {
        tCSVValidator0 = new TCSVValidator(tPolicy0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Given policy hasn't been closed. Did you call that policy's done () method?
         //
         verifyException("org.ph394b8fe.validator.TCSVValidator", e);
      }
  }
}
